# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # FreeMarker 配置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
# MyBatis 配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    
# MyBatis 日志
logging:
  level:
    org.spring.springboot.dao: debug