spring:
  druid:
    default:      # druid连接池默认配置项
      url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5                                   # 链接池初始化大小
      min-idle: 5                                       # 链接池中最少要保留的链接数
      max-active: 50                                    # 链接池中最大的链接数
      max-wait: 3000                                    # 链接池中最大等待的链接数
      filters: wall,stat                                # 启用过滤器
      validation-query: SELECT 1                        # 验证数据库连接的有效性
      test-while-idle: true                             # 链接在空闲时测试 
      remove-abandoned-timeout-millis: 1800             # 关闭超过30分钟的空闲连接，1800秒，也就是30分钟
      log-abandoned: true
    stat:         # druid监控配置
      enable: true                                      # 启用druid监控控制台
      login-username: druid                             # 用户名
      login-password: druid                             # 用户名
  mybatis:        # mybatis配置参数
    configuration:                                      # mybatis具体的配置参数,所有的mybatis实例都会使用该配置
      cache-enabled: true                               # 该配置影响的所有映射器中配置的缓存的全局开关。
      aggressive-lazy-loading: false                    # 按需加载。当开启时，任何方法的调用都会加载该对象的所有属性。否则，每个属性会按需加载
      lazy-loading-enabled: true                        # 延迟加载的全局开关。当开启时，所有关联对象都会延迟加载。 特定关联关系中可通过设置fetchType属性来覆盖该项的开关状态。
      map-underscore-to-camel-case: true                # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射。
    nodes:
      colg:                                              # 该数据源的名字，可以配置多个数据源
        mapper: MYSQL                                   # mybatis通用mapper使用的mapper接口集合,mysqldb时使用使用 MYSQL,SqlServer 时使用MSSQL,其它db类型时使用DEFAULT， 默认值是 DEFAULT
        base-package: org.spring.springboot.dao         # Mapper.java 接口路径
        mapper-package: classpath:mapper/*.xml          # Mapper.xml 配置文件位置
        master:
          url: ${spring.druid.default.url}
          
logging:
  level:
    org.spring.springboot.dao: debug