# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
# MyBatis配置
mybatis:
#  type-aliases-package: org.spring.springboot.domain
  mapper-locations:
    - classpath:mapper/*.xml

# MyBatis日志
logging:
  level:
    org.spring.springboot.dao: debug