# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  dubbo:
    application:
      name: springboot-dubbo-server
    registry:
      protocol: zookeeper
      address: 192.168.21.101:2181
    protocol:
      name: dubbo
      port: 20880
    scan: org.spring.springboot.service
    
# Mybatis 配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    
# Mybatis 日志级别
logging:
  level:
    org.spring.springboot.dao: debug