# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # FreeMarker 配置
  freemarker:
    template-loader-path:
      - classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
      
    
# MyBatis 配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    
# MyBatis 日志
logging:
  level:
    org.spring.springboot.dao: debug